{"name": "test_login_user_with_incorrect_login_and_password", "status": "passed", "description": "Проверка невозможности логина пользователя с неверным логином и паролем.Получаем ошибку 401", "steps": [{"name": "Логин пользователя в системе", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'foti_2004@example.org', 'password': '2@7X)twS7Y', 'name': 'Пестова Алина Вениаминовна'}"}], "start": 1717267069534, "stop": 1717267069736}], "start": 1717267069482, "stop": 1717267069736, "uuid": "a5bcde8e-59e4-46a7-9fbc-4af8757c525c", "historyId": "3a1956904ff880a4bcd6a84684410a2b", "testCaseId": "3a1956904ff880a4bcd6a84684410a2b", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_with_incorrect_login_and_password", "labels": [{"name": "story", "value": "Ручка /api/auth/login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "WIN-BHU1OVNKOHE"}, {"name": "thread", "value": "13424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}